language: haskell

ghc:
  - 7.0.4
  - 7.4.2
  - 7.6.3
  - 7.8.3

install:
  - cabal update
  - |
    if [ $GHCVER = "7.0.4" ]; then
      cabal install -j --only-dependencies
    else
      cabal install -j --only-dependencies --enable-tests

script:
  - |
    if [ $GHCVER = "7.0.4" ]; then
      cabal configure
      cabal build
    else
      cabal configure --enable-tests
      cabal build
      cabal test
