language: haskell

env:
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.3
  - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=head

install:
  - cabal update
  # There's a bug in double-conversion (https://github.com/bos/double-conversion/issues/8)
  # that seems to occasionally break Travis-CI's builds. For the time being,
  # I'll disable the test-suite.

  #- cabal install -j --only-dependencies --enable-tests
  - cabal install -j --only-dependencies

script:
  # There's a bug in double-conversion (https://github.com/bos/double-conversion/issues/8)
  # that seems to occasionally break Travis-CI's builds. For the time being,
  # I'll disable the test-suite.
  
  #- cabal configure --enable-tests
  - cabal configure
  - cabal build
  #- cabal test
